### ISSUE TITLE
Peer Review - Continuation

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guide-okd#10]
Here to address the issues from #6 that couldn't be automatically addressed with the peer review PR #7. Most of these seem like UI issues that I don't think I can address without help from the UI team. Keeping it here to address later.

- [ ] on Mac, when you copy the curl command, and paste it in the terminal (default terminal, vscode) 
it looks like: 
`curl http://\[host-name\]/system/properties` instead of 
`curl http://[host-name]/system/properties`.
It's fine for copying and pasting into other applications in Mac though (such as browsers, text files)

- [ ] code on sidepane hides the appropriate things, but if you click the file header on the codepane, it stops hiding those parts and shows the entire file

- [ ] hotspots in yaml file are highlighting extra blank lines below
    ![image](https://user-images.githubusercontent.com/46586499/70468975-1ea88a80-1a96-11ea-8c01-ed810fe72fa1.png)

**Comment by MaiHameed** [comment]
> on Mac, when you copy the curl command, and paste it in the terminal (default terminal, vscode) 
it looks like: 
`curl http://\[host-name\]/system/properties` instead of 
`curl http://[host-name]/system/properties`.
It's fine for copying and pasting into other applications in Mac though (such as browsers, text files)

Tried this on the default terminal app on Mac, same error. Doesn't happen on my configured zsh terminal though.

**Comment by gkwan-ibm** [comment]
close
- this guide was deprecated
