### ISSUE TITLE
update testApp.sh

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-okd#87]
Do not use `oc` for testing
- remove `sudo ../scripts/setupOpenshift.sh` from `.github/workflows/test.yml`
- update the `scripts/testApp.sh` to use `docker` to verify the app instead of `oc`
  - similar to https://github.com/OpenLiberty/guide-getting-started/blob/prod/scripts/testApp.sh
  - run mvn commands to build the app and verify the app by `mvn verify`
  - run docker to build and run the app, check the url

**Comment by shin19991207** [comment]
Addressed in https://github.com/OpenLiberty/guide-okd/pull/89
